SELECT COUNT(*) FROM ASTEROIDS;

SELECT AVG(ABSOLUTE_MAGNITUDE_H) FROM ASTEROIDS;

SELECT MAX(ABSOLUTE_MAGNITUDE_H) FROM ASTEROIDS;

SELECT IS_POTENTIALLY_HAZARDOUS, COUNT(*)
FROM ASTEROIDS
GROUP BY IS_POTENTIALLY_HAZARDOUS;